### ISSUE TITLE
How to manage the behavior of elements in a custom block?

### ISSUE THREAD

**Issue by AlexBrainhow** [dariuszdawidowski/metaviz-editor#1]
I downloaded an asset from the Unity Asset Store, it uses a plugin to create special blocks. I wanted to modify it so that it would be possible to change the sprite of the active character to the desired emotion. However, when I added a second selector there, they overlapped each other. How can I control the position and size of these elements?

![image](https://github.com/user-attachments/assets/bd4277ac-33ba-439e-b721-c89b009c735f)
![image](https://github.com/user-attachments/assets/53f8f513-14e5-44d4-a14e-f4db18639507)

`
/* Node Quest Dialogue */

class NodeQuestDialogue extends MetavizNode {

    constructor(args) {
        super(args);

        // Meta defaults
        if (!('name' in this.params)) this.params['name'] = 'Isaac';

        // Size
        this.setSize({width: 500, height: 135});

        // Characters
        this.characters = {
            'Isaac': {name: 'Isaac', avatar: 'Demo/VisualNovel/Sprites/Characters/Taku-avatar.png'},
            'Logan': {name: 'Logan', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Zale': {name: 'Zale', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Lora': {name: 'Lora', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Pendragast': {name: 'Pendrogast', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Golaser': {name: 'Golaser', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Security': {name: 'Security', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Merchant': {name: 'Merchant', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
            'Worker': {name: 'Worker', avatar: 'Demo/VisualNovel/Sprites/Characters/Aya-avatar.png'},
        };
        this.avatars = Object.keys(this.characters).reduce((result, key) => (result[key] = this.characters[key].avatar, result), {});

        this.emotions = {
            'Normal': {name: 'Normal'},
            'Happy': {name: 'Happy'},
            'Angry': {name: 'Angry'},
            'Sad': {name: 'Sad'},
        };

        // Controls
        this.addControls({

            // Bitmap control
            bitmap: new MetavizControlBitmap({
                uri: this.avatars[this.params.name]
            }),

            // Select charactor
            name: new MetavizControlSelect({
                value: this.params.name,
                options: Object.keys(this.characters).reduce((result, key) => (result[key] = this.characters[key].name, result), {}),
                onChange: (value) => {
                    this.controls.bitmap.set(this.avatars[value]);
                    metaviz.editor.history.store({action: 'param', node: {id: this.id}, params: {name: value}, prev: {name: this.params.name}});
                    this.params.name = value;
                }
            }),

            // Select emotion
            emote: new MetavizControlSelect({
                value: this.params.emote,
                options: Object.keys(this.emotions).reduce((result, key) => (result[key] = this.emotions[key].name, result), {}),
                onChange: (value) => {
                    metaviz.editor.history.store({action: 'param', node: {id: this.id}, params: {emote: value}, prev: {emote: this.params.emote}});
                    this.params.emote = value;
                }
            }),

            // Text content
            textarea: new MetavizControlRichText({
                name: 'text',
                value: this.params.text,
                onChange: (value) => {
                    metaviz.editor.history.store({action: 'param', node: {id: this.id}, params: {text: value}, prev: {text: this.params.text}});
                    this.params.text = value;
                }
            }),

        });

        // Meta setter
        this.params.set = (key, value) => {

            this.params[key] = value;

            if (key == 'name') {
                this.controls.name.set(value);
                this.controls.bitmap.set(this.avatars[value]);
            }
            else if (key == 'emote'){
                this.controls.emote.set(value);
            }
            else if (key == 'text') {
                this.controls.textarea.set(value);
            }
        }

        // Sockets
        this.addSockets();
    }

    /**
     * Selection
     */

    select() {
        super.select();
        this.controls.textarea.edit(true);
    }

    deselect() {
        super.deselect();
        this.controls.textarea.edit(false);
    }

}

global.registry.add({node: NodeQuestDialogue, menu: 'Visual Novel', name: 'Dialogue', slug: 'quest-dialogue'});
`

**Comment by dariuszdawidowski** [comment]
Hello,

Solution is to name your controls and tweak them in css.

1. Name your MetavizControlSelect objects

```
 name: new MetavizControlSelect({
            name: 'name',            
            value: this.params.name,
            ...

 emote: new MetavizControlSelect({
            name: 'emote',
            value: this.params.emote,
            ...
```
So this will be projected into class names .metaviz-control-select-**name** and .metaviz-control-select-**emote**

2. Style it in the css however you prefer
For example main element could be css grid

```
.metaviz-node-quest-dialogue {
    min-width: 380px;
    min-height: 174px;
    border-radius: 20px;
    display: grid;
    justify-items: center;
    align-items: center;
    grid-template-areas: "avtr txt txt"
                         "inp1 txt txt"
                         "inp2 txt txt";
}

.metaviz-node-quest-dialogue .metaviz-control-select-name {
    grid-area: inp1;
}

.metaviz-node-quest-dialogue .metaviz-control-select-emote {
    grid-area: inp2;
}

/* also bitmap should be placed in grid-area: avtr; and richtext in grid-area: txt; */

```

I hope this helps. Please let me know if doesn't.

**Comment by AlexBrainhow** [comment]
Thanks for the pretty quick reply!
It really helped)

I think in the future you should think about blocks for changing sprites, scenes, music, playing sounds and other things for visual novels)

I will do it myself, but still thanks for a pretty convenient base for this!

**Comment by dariuszdawidowski** [comment]
I'm glad it helped!

The project is in a very early stage of development, the elements you mentioned will be in the future, but not too soon. Currently, the project is mainly supported by the cryptocurrency industry and in the coming months I will focus on it - to make it work entirely on blockchain.

It's good to hear that you are making your own elements, at this stage it's a good base for making your own tool.

If you need help with new elements - I will try to help.
